Submit binary file updates as a single PR
ppy/SDL3-CS pull request #161
Opened 2024-09-22 16:32 UTC by smoogipoo

Super spammy + manual merge process.

The `native` dir is compressed as a `tar` to not deal with RIDs and decompressed into the repository root. Android JAR is uploaded as-is because it's a single file.

Run: https://github.com/smoogipoo/SDL3-CS/actions/runs/10982512435
PR: https://github.com/smoogipoo/SDL3-CS/pull/49

2024-09-22 23:02 UTC, Susko3 requested changes

2024-09-26 00:14 UTC, Susko3 commented on .github/workflows/build.yml
> +        run: tar -cf native-${{ matrix.platform.name }}.tar native
Likely the only change necessary. Same change should work for `android` and `ios`.
```suggestion
      - name: Compress native directory
        run: tar -cf native-${{ matrix.platform.name }}.tar native/${{ matrix.platform.name }}
```

2024-09-26 09:19 UTC, smoogipoo commented on .github/workflows/build.yml
> +        run: tar -cf native-${{ matrix.platform.name }}.tar native
> Wouldn't extracting those different tarballs overwrite the files

It overwrites files, not entire directories. That being said, I think your suggestion is fine.

2024-09-26 09:30 UTC, smoogipoo commented on .github/workflows/build.yml
> +        run: tar -cf native-${{ matrix.platform.name }}.tar native
Oh, I see what you mean, because the directories already contain the files... Nice catch.

2024-10-01 18:24 UTC, Susko3 approved these changes

2024-10-01 18:25 UTC, merged