Add libs for linux-arm64 and linux-arm
ppy/SDL3-CS pull request #56
Opened 2024-05-15 15:37 UTC by kvnp

Continues the work of https://github.com/ppy/SDL3-CS/pull/55.

2024-05-15 18:31 UTC, Susko3 commented on .github/workflows/build.yml
> +        shell: bash
Has this been tested on windows? I think this will now use [WSL](https://learn.microsoft.com/en-us/windows/wsl/) instead of PowerShell like it used to.

2024-05-15 18:33 UTC, Susko3 commented on build.sh
> +fi
Aren't flags supposed to be set in the OS matrix?

2024-05-15 18:34 UTC, smoogipoo requested changes
https://github.com/smoogipoo/SDL3-CS/actions/runs/9099250769

macOS builds seem to have broken, it's not immediately obvious why but it's fine on master so it has to be related to this PR (https://github.com/smoogipoo/SDL3-CS/actions/runs/9099367179).

2024-05-15 19:10 UTC, kvnp commented on .github/workflows/build.yml
> +            -e BUILD_TYPE=${{ env.BUILD_TYPE }}
Great solution, I'll try that. Interestingly, once I added dummy libs for linux-arm64 and linux-arm, the failure disappeared. That's why I added them in the last PR.

2024-05-15 19:51 UTC, kvnp commented on build.sh
> +fi
You are right, moved.

2024-05-15 19:51 UTC, kvnp commented on build.sh
Oops, forgot to change the permissions after recreating the PR.

2024-05-15 19:55 UTC, kvnp commented on .github/workflows/build.yml
> +        shell: bash
Yes, it uses the bash binary bundled with Git for Windows or MSYS, so no WSL interop.

2024-05-17 21:54 UTC, kvnp commented
> https://github.com/smoogipoo/SDL3-CS/actions/runs/9099250769
> 
> macOS builds seem to have broken, it's not immediately obvious why but it's fine on master so it has to be related to this PR (https://github.com/smoogipoo/SDL3-CS/actions/runs/9099367179).

It finally works now. The problem was that the quotes in the flags were previously ignored when passing them via expressions to the cmake calls. After the change to pass them as env vars, they were no longer ignored, causing these "not separated tokens" errors. This only became apparent after I tried to build via ninja, see the following log snippets.

<details>
<summary>Output without Ninja</summary>
  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/CMakeFiles/SDL3-shared.dir/DependInfo.cmake:11:
  Syntax Warning in cmake code at column 135

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/CMakeFiles/SDL3-shared.dir/DependInfo.cmake:11:
  Syntax Warning in cmake code at column 195

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/CMakeFiles/SDL3-shared.dir/DependInfo.cmake:12:
  Syntax Warning in cmake code at column 83

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build/CMakeFiles/SDL3-shared.dir/DependInfo.cmake:12:
  Syntax Warning in cmake code at column 133
</details>


<details>
<summary>Output with Ninja</summary>
[1/226] Building C object 'CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h.pch'
FAILED: CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h.pch 
/Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DDLL_EXPORT -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=2 -DSDL_BUILD_MINOR_VERSION=1 -DUSING_GENERATED_CONFIG_H -I/Users/runner/work/SDL3-CS/SDL3-CS/build/include-config-release -I/Users/runner/work/SDL3-CS/SDL3-CS/build/include -I/Users/runner/work/SDL3-CS/SDL3-CS/include -I/Users/runner/work/SDL3-CS/SDL3-CS/src -I/Users/runner/work/SDL3-CS/SDL3-CS/include/SDL3 -O3 -DNDEBUG -arch "x86_64" -isysroot /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min="10.14" -fPIC -fvisibility=hidden -Wall -Wundef -fno-strict-aliasing -Wdocumentation -Wdocumentation-unknown-command -fcomment-block-commands=threadsafety -Wshadow -Wno-unused-local-typedefs -Wimplicit-fallthrough -fcolor-diagnostics -idirafter/Users/runner/work/SDL3-CS/SDL3-CS/src/video/khronos -Wno-error=deprecated-declarations -D_REENTRANT -fobjc-arc -Winvalid-pch -Xclang -emit-pch -Xclang -include -Xclang /Users/runner/work/SDL3-CS/SDL3-CS/build/CMakeFiles/SDL3-shared.dir/cmake_pch_\"x86_64\".h -x c-header -MD -MT 'CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h.pch' -MF CMakeFiles/SDL3-shared.dir/cmake_pch_\"x86_64\".h.pch.d -o 'CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h.pch' -c '/Users/runner/work/SDL3-CS/SDL3-CS/build/CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h.c'
<built-in>:1:90: warning: extra tokens at end of #include directive [-Wextra-tokens]
#include "/Users/runner/work/SDL3-CS/SDL3-CS/build/CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h"
                                                                                         ^
                                                                                         //
<built-in>:1:10: fatal error: '/Users/runner/work/SDL3-CS/SDL3-CS/build/CMakeFiles/SDL3-shared.dir/cmake_pch_' file not found
#include "/Users/runner/work/SDL3-CS/SDL3-CS/build/CMakeFiles/SDL3-shared.dir/cmake_pch_"x86_64".h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
[2/226] Building OBJC object CMakeFiles/SDL3-shared.dir/src/file/cocoa/SDL_iostreambundlesupport.m.o
[3/226] Building OBJC object CMakeFiles/SDL3-shared.dir/src/misc/macos/SDL_sysurl.m.o
[4/226] Building OBJC object CMakeFiles/SDL3-shared.dir/src/camera/coremedia/SDL_camera_coremedia.m.o
[5/226] Building C object CMakeFiles/SDL3-shared.dir/src/dynapi/SDL_dynapi.c.o
ninja: build stopped: subcommand failed.
</details>

2024-05-18 04:18 UTC, smoogipoo approved these changes

2024-05-18 04:19 UTC, smoogipoo commented
Thanks a lot!

2024-05-18 04:19 UTC, merged