Update bindings
ppy/SDL3-CS pull request #91
Opened 2024-06-25 18:26 UTC by hwsmm

I actually didn't mean to work on this. I had updated my system SDL package to master, and osu! was straight up broken, so I tried updating bindings to spend some free time.

I don't mean to take over maintaining bindings. This is probably just a one-time thing unless my accidental package update breaks things again...

There may be some things I may have missed since this is my first time updating bindings. Please let me know if there are any!

2024-06-26 23:12 UTC, smoogipoo approved these changes

2024-06-26 23:16 UTC, smoogipoo commented
> and osu! was straight up broken

This shouldn't happen because we package our own SDL3 lib. Would be curious if you could run osu! with `LD_DEBUG=libs` and paste that output, as it's very concerning.

2024-06-27 01:48 UTC, hwsmm commented
I guess I should have been more clear. I use my system SDL3 *intentionally* because SDL3 we build is currently missing PipeWire support and some minor things I want.

It uses bundled SDL3 without my script, so you don't need to worry about that.

2024-07-01 19:56 UTC, Susko3 requested changes
Missing some SDL3-CS specifics, seems fine otherwise. I can do the changes if you wish.

2024-07-01 19:56 UTC, Susko3 commented on SDL3-CS/SDL3/ClangSharp/SDL_mouse.g.cs
> +        [return: NativeTypeName("SDL_MouseButtonFlags")]
`SDL_MouseButtonFlags` should be added as a `[Typedef] enum`, replacing the manually-added `SDLButtonMask`.

You can search for `[Typedef]` to see how to add it. After adding it, just rerun the python script.

2024-07-01 19:56 UTC, Susko3 commented on SDL3-CS/SDL3/ClangSharp/SDL_pen.g.cs
>          public static extern uint SDL_GetPenCapabilities(SDL_PenID instance_id, SDL_PenCapabilityInfo* capabilities);
`SDL_PenCapabilityFlags` should also be added as a `[Typedef] enum`.

2024-07-01 19:56 UTC, Susko3 commented on SDL3-CS/SDL3/ClangSharp/SDL_video.g.cs
> +        public static extern SDL_Window** SDL_GetWindows(int* count);
This fits the `SDLPointerArray` pattern.

2024-07-02 14:45 UTC, hwsmm commented
I applied requested changes and updated bindings!

2024-07-14 13:57 UTC, Susko3 approved these changes
LGTM, checked that generating the bindings locally matches changes in this PR.

2024-07-16 02:05 UTC, merged